#!/usr/bin/env python

from intermittent_monitoring.monitor_stats import *

if __name__ == '__main__':
    areas = [1, 2, 3]
    robots = [0]
    stats_listener = StatsListener(areas=areas, robots=robots, sleep=10)

    #Dec step = 1
    # filename = 'treebased_d1_stats.pkl'
    # print("Listening to F-measure of Areas: {}. Battery of robots: {}".format(areas, robots))
    # result = stats_listener.save_recorded_array(t_operation=2000, filename=filename)
    # print("Stored data:", result)


    #Dec step = 2
    # filename = 'treebased_d2_stats.pkl'
    # print("Listening to F-measure of Areas: {}. Battery of robots: {}".format(areas, robots))
    # result = stats_listener.save_recorded_array(t_operation=1000, filename=filename)
    # print("Stored data:", result)
    #
    #
    #Dec step = 3
    filename = 'treebased_d3_stats_v2.pkl'
    print("Listening to F-measure of Areas: {}. Battery of robots: {}".format(areas, robots))
    result = stats_listener.save_recorded_array(t_operation=2000, filename=filename)
    print("Stored data:", result)
    #
    #
    #Dec step = 4
    # filename = 'treebased_d4_stats.pkl'
    # print("Listening to F-measure of Areas: {}. Battery of robots: {}".format(areas, robots))
    # result = stats_listener.save_recorded_array(t_operation=2000, filename=filename)
    # print("Stored data:", result)
    #
    # #Dec step = 6
    # filename = 'treebased_d6_stats.pkl'
    # print("Listening to F-measure of Areas: {}. Battery of robots: {}".format(areas, robots))
    # result = stats_listener.save_recorded_array(t_operation=2000, filename=filename)
    # print("Stored data:", result)

    # # Dec step = 10
    # filename = 'treebased_d10_stats.pkl'
    # print("Listening to F-measure of Areas: {}. Battery of robots: {}".format(areas, robots))
    # result = stats_listener.save_recorded_array(t_operation=2000, filename=filename)
    # print("Stored data:", result)
