
debug_mode: 1
method: $(arg method) # method that is running
nrobots: $(arg nrobots)    # number of robots on the team
nareas: $(arg nareas) #number of areas to preserve
placement: $(arg placement) #placement of areas
dec_steps: $(arg dsteps) #number of decision steps
t_operation: $(arg tframe) #total duration of the operation
file_sampled_areas: $(arg fileposes) #file name of sampled areas
history_data: $(arg history_data) #filename for history data to be used to train time-series model
history_decisions: $(arg history_decisions) #filename for history decisions accomplished to be used to train time-series model
file_data_dump: $(arg fileresult) #file name for data dump
inference: $(arg inference) #type of heuristic for inference on decay param
save: $(arg save) #save data

gamma: $(arg discount) #0.25 #discount factor for future losses/rewards: [0, 1]. If gamma=0, present looking. Else if gamma=1, all future rewards are treated equally with present reward
robot_velocity: 1.0 #Linear velocity of robot; we assume linear and angular are relatively equal
max_fmeasure: 100 # Max F-measure of an area
max_battery: 100 #Max battery, 100
battery_reserve: 20 #battery reserve
f_thresh: [80, 50] #(safe, crit)
batt_consumed_per_time: [0.10, 0.10] #(travel, restoration)
restoration: 25 #F-measure/battery.py units per second restored
noise: 0.25 #noise/error in navigation and restoration #TODO: Can we start with 0.0?
move_base_tolerance: 0.5

#Uncertainty params
win_size: 3 #window size for the moving average forecast. TODO: This can be just a hyper-parameter in moving average script
nvisits_thresh: $(arg nvisits) #threshold of data collected to trigger training/update of time-series model
discrepancy_thresh: 0.05 #threshold of discrepancy betweeen belief decay and measured decay to trigger training/update of timeseries model
learning_rate: 0.75 #learning rate

#Reinforcement learning params
exploration: $(arg exploration) #tunable exploration parameter
correlation_info: [[1, 2, 1.0], [2, 1, 1.0], [3, 4, 1.0], [4, 3, 1.0], [5, 6, 1.0], [6, 5, 1.0], [7, 8, 1.0], [8, 7, 1.0]] #correlation information among areas with their magnitude
sigma: 1.0 #standard deviation of the normal distribution for thompson sampling

#RMA search
frontier_length: None #Length of frontier for RMA search; set as None for full frontier or positive integer for truncated